export const UPCOMING_MATCHES_LOADING = 'UPCOMING_MATCHES_LOADING'
export const UPCOMING_MATCHES_SUCCESS = 'UPCOMING_MATCHES_SUCCESS'
export const UPCOMING_MATCHES_FAILURE = 'UPCOMING_MATCHES_FAILURE'